[package]
name = "fizzyhex/matter-ns"
description = "Fork of Matter with negative entity IDs on the server."
version = "0.6.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["example", "docs", "Packages", ".moonwave", "build", "pages", "tests", "AttackOfTheKillerRoombas.rbxl", "AttackOfTheKillerRoombas.rbxl.lock", "matter.rbxl", "matter.rbxm", "roblox.toml"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"